version: "2"
services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000/tcp
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
